### ISSUE TITLE
API ability to get "leading" events for query period

### ISSUE THREAD

**Issue by jantman** [ActivityWatch/aw-server#53]
First I'd like to express again my thanks for such a wonderful and helpful project!

I've been using ActivityWatch for about two weeks now, and have also implemented a few very custom watchers for my own use cases. I'm currently running off of the latest tag, v0.8.0b7.

One thing I've noticed though that is a bit annoying to me is the Events and Query API behavior (and corresponding UI behavior) for long events that begin prior to the query period being cut off. For example, if I was AFK for a long amount of time until 30 minutes ago, and query for events in the last hour (or pull up the Timeline view in the UI for the last hour), I only see the "not-afk" event that started 30 minutes ago... and blank space leading up to it.

It seems to me like it would be really helpful if the events and query API endpoints had an option to return a "leading" event, if there's an event that started before the start of the query period but ended during the query period. I could also see this being represented in the timeline view with some sort of special icon or left border, indicating that the event began prior to the currently-viewed period.

**Comment by jantman** [comment]
I looked around in the ``aw-core`` code a bit, and it seems like this is a bigger ask than I thought because (1) the ``EventModel`` stores a datetime start and decimal duration, and (2) SQLite doesn't have any native DateTime type, so it's not possible (or at least very complicated) to query events based on "end time" (a derived/hybrid value) in SQL.

It also seems like, from what I can tell based on some other issues and the ability to POST an event via the API with a specified ID, we can't count on event IDs being in chronological order...

**Comment by ErikBjare** [comment]
We're aware of this unfortunate behavior (it's been discussed elsewhere, can't remember where though) and there's actually a fix in the works with the new sqlite datastore @johan-bjareholt has been working on in aw-core: https://github.com/ActivityWatch/aw-core/pull/57

That PR has been in the works quite a while though, and been kinda on ice as it needs a database migration that is critical we don't fuck up.

The easiest way to currently get leading events is to simply over-query and then cut off the excess on the client side.

**Comment by johan-bjareholt** [comment]
@jantman This is all overcomplicating things. The solution we used in the future sqlite storage is instead of saving the duration we save the endtime, so if we have both starttime and endtime we don't need to over-querying as we now have the data to get the exact right events. With starttime and endtime we also no longer need the duration since endtime-starttime=duration so the database didn't even grow in size. We also no longer save datetimes as strings since it doesn't really make any sense as long as you don't care about timezones.

I have used multiple ORMs before and almost every time I try to do something slightly complicated I start looking at how the underlying database works rather than how the ORM works which defeats the purpose of an ORM. SQLite is not that complicated either, so just using SQLite directly makes more sense to us.

**Comment by jantman** [comment]
Ok, that all makes sense. I'll be looking forward to a release with the sqlite storage and migrations.

**Comment by jantman** [comment]
Ok, yeah, I'd be happy to test it! I have a 3-day weekend so I should definitely have some time to.

Right now I'm installing from git using a clone of the main activitywatch repo, installed per the source install docs. Do you know if I should be OK to just update aw-server to development or whether other submodules need to be updated as well?

I'll stick with the python ;) it's by far my strongest language, and a big reason of why I first checked out ActivityWatch.

**Comment by johan-bjareholt** [comment]
aw-server heavily depends on aw-core so you need that as well with the newest version most likely.

**Comment by jantman** [comment]
I was just about to give this a test and ran into a bit of confusion for me... you said I should just be able to check out aw-server to the development branch... but aw-server currently has six ``dev/`` branches, none of which share the same name as the aw-core ``dev/sqlite`` branch that matches up with https://github.com/ActivityWatch/aw-core/pull/57

I tried checking out aw-core on the ``dev/sqlite`` branch and aw-server on the master branch, but that renders aw-server completely unusable with SQLite threading errors (i.e. API calls result in a 500 error logging ``sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140560724657664 and this is thread id 140560642361088.``).

I'm unable to check the migrations because I can't get a single GET request to succeed.

My process for the upgrade was as follows:

- stop aw-server, watchers, qt
- switch my clone to https://github.com/jantman/activitywatch/tree/jantman-current
- make build (note this threw some npm errors for "vis")
- back up ``~/.local/share/activitywatch/aw-server/peewee-sqlite.v2.db``
- ``sed -i 's/peewee/sqlite/' ~/.config/activitywatch/aw-server/aw-server.ini``
- run ``aw-server --verbose`` to ensure it looks right:

```
$ aw-server --verbose
2019-01-21 18:09:15 [INFO ]: Using storage method: sqlite  (aw_server.main:26)
2019-01-21 18:09:15 [INFO ]: Starting up...  (aw_server.main:31)
2019-01-21 18:09:15 [INFO ]: Using database file: /home/jantman/.local/share/activitywatch/aw-server/sqlite.v1.db  (aw_datastore.storages.sqlite:69)
2019-01-21 18:09:15 [INFO ]: Created new SQlite db file  (aw_datastore.storages.sqlite:81)
2019-01-21 18:09:15 [INFO ]: Migrating database from peewee v2 to sqlite v1  (aw_datastore.migration:31)
2019-01-21 18:09:15 [INFO ]: Using database file: /home/jantman/.local/share/activitywatch/aw-server/peewee-sqlite.v2.db  (aw_datastore.storages.peewee:89)
2019-01-21 18:09:15 [INFO ]: Migrating bucket aw-watcher-window_phoenix.jasonantman.com  (aw_datastore.migration:38)
2019-01-21 18:09:19 [INFO ]: Migrating bucket aw-watcher-afk_phoenix.jasonantman.com  (aw_datastore.migration:38)
2019-01-21 18:09:19 [INFO ]: Migrating bucket aw-watcher-web-chrome  (aw_datastore.migration:38)
2019-01-21 18:09:21 [INFO ]: Migrating bucket aw-watcher-web-firefox  (aw_datastore.migration:38)
2019-01-21 18:09:22 [INFO ]: Migrating bucket aw-watcher-manual-flaskweb_phoenix.jasonantman.com  (aw_datastore.migration:38)
2019-01-21 18:09:22 [INFO ]: Migrating bucket aw-watcher-hass-device  (aw_datastore.migration:38)
2019-01-21 18:09:22 [INFO ]: Migrating bucket aw-watcher-working_phoenix.jasonantman.com  (aw_datastore.migration:38)
2019-01-21 18:09:22 [INFO ]: Migrating bucket aw-watcher-hass-desk-standing  (aw_datastore.migration:38)
2019-01-21 18:09:22 [INFO ]: Migration of peewee v2 to sqlite v1 finished  (aw_datastore.migration:50)
 * Serving Flask app "aw-server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
2019-01-21 18:09:22 [INFO ]:  * Running on http://0.0.0.0:5600/ (Press CTRL+C to quit)  (werkzeug:88)
2019-01-21 18:09:30 [ERROR]: Exception on /api/0/buckets/aw-watcher-web-chrome/heartbeat [POST]  (flask.app:1761)
Traceback (most recent call last):
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/aw_server/rest.py", line 233, in post
    event = app.api.heartbeat(bucket_id, heartbeat, pulsetime)
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/aw_server/api.py", line 26, in g
    if bucket_id not in self.db.buckets():
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/aw_datastore/datastore.py", line 48, in buckets
    return self.storage_strategy.buckets()
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/aw_datastore/storages/sqlite.py", line 113, in buckets
    c = self.conn.cursor()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140560724657664 and this is thread id 140560642361088.
2019-01-21 18:09:30 [INFO ]: 500 (127.0.0.1): POST /api/0/buckets/aw-watcher-web-chrome/heartbeat?pulsetime=80 HTTP/1.1  (flask:25)
2019-01-21 18:09:50 [ERROR]: Exception on /api/0/buckets/aw-watcher-web-chrome/heartbeat [POST]  (flask.app:1761)
Traceback (most recent call last):
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/aw_server/rest.py", line 233, in post
    event = app.api.heartbeat(bucket_id, heartbeat, pulsetime)
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/aw_server/api.py", line 26, in g
    if bucket_id not in self.db.buckets():
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/aw_datastore/datastore.py", line 48, in buckets
    return self.storage_strategy.buckets()
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/aw_datastore/storages/sqlite.py", line 113, in buckets
    c = self.conn.cursor()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140560724657664 and this is thread id 140560642361088.
2019-01-21 18:09:50 [INFO ]: 500 (127.0.0.1): POST /api/0/buckets/aw-watcher-web-chrome/heartbeat?pulsetime=80 HTTP/1.1  (flask:25)
2019-01-21 18:12:23 [ERROR]: Exception on /api/0/buckets/ [GET]  (flask.app:1761)
Traceback (most recent call last):
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/aw_server/rest.py", line 115, in get
    return app.api.get_buckets()
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/aw_server/api.py", line 50, in get_buckets
    buckets = self.db.buckets()
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/aw_datastore/datastore.py", line 48, in buckets
    return self.storage_strategy.buckets()
  File "/opt/activitywatch/venv/lib/python3.7/site-packages/aw_datastore/storages/sqlite.py", line 113, in buckets
    c = self.conn.cursor()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139670367213056 and this is thread id 139670322161408.
2019-01-21 18:12:23 [INFO ]: 500 (127.0.0.1): GET /api/0/buckets/ HTTP/1.1  (flask:25)
```

(note: yes, I'm running bound to 0.0.0.0; yes, I'm well aware of the implications of that)

**Comment by ErikBjare** [comment]
It should be a really easy fix though, I think we just need to call set `treaded=False` somewhere: https://stackoverflow.com/questions/38876721/handle-flask-requests-concurrently-with-threaded-true

**Comment by jantman** [comment]
There's actually an example of this in the Flask patterns docs, which shows using the ``flask.g`` object proxy for sqlite connections: http://flask.pocoo.org/docs/0.12/patterns/sqlite3/

I've got a few things on my plate in the next few days, but I'll _try_ to work up an aw-server branch to fix this.

**Comment by johan-bjareholt** [comment]
@ErikBjare Good point, did a quick untested PR https://github.com/ActivityWatch/aw-server/pull/54
